FROM alpine:3.15.0@sha256:c74f1b1166784193ea6c8f9440263b9be6cae07dfe35e32a5df7a31358ac2060 AS base

RUN apk add --update --no-cache \
	nodejs~=16 \
	qemu-img \
	qemu-system-aarch64 \
	qemu-system-arm

WORKDIR /root

FROM base AS build

RUN apk add --update --no-cache npm

COPY package.json *.js ./
RUN npm i

FROM base AS run

COPY --from=build /root/ /root/

RUN mkdir -p /etc/qemu \
	&& echo "allow all" > /etc/qemu/bridge.conf \
	&& chmod 0640 /etc/qemu/bridge.conf

CMD ./cli.js
