FROM ubuntu:20.04

ARG DEBIAN_FRONTEND=noninteractive
ENV TZ=Etc/UTC

WORKDIR /app

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    ca-certificates \
    ovmf \
    qemu-system-x86 \
    qemu-utils \
    unzip \
    wget && \
    rm -rf /var/lib/apt/lists/*

COPY virt-start.sh start.sh

RUN chmod +x start.sh

CMD ["/app/start.sh"]
